name: dashboard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http : ^0.13.5
  path_provider: ^2.0.10
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  syncfusion_flutter_maps: ^20.4.54
  fl_chart: ^0.69.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

assets :
  - plane_loading.gif
  - amadeus.png


